spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: search-service
          uri: http://localhost:8080/
          predicates:
            - Path=/search/**

        - id: book-service
          uri: http://localhost:8087/
          predicates:
            - Path=/book/**
            
        - id: checkin-service
          uri: http://localhost:8090/
          predicates:
            - Path=/checkin/**

        - id: AdminSecurity-service
          uri: http://localhost:8088/
          predicates:
            - Path=/admin/**

        - id: UserSecurity-service
          uri: http://localhost:8683/
          predicates:
            - Path=/user/**

        - id: Admin-service
          uri: http://localhost:8089/
          predicates:
            - Path=/adminpage/**
          

server:
  port:   30003 

